//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXport_EXcel_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_registration
    {
        public string Email { get; set; }
        public Nullable<int> Password { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public int id { get; set; }
    }
}
